version: "3.8"

services:
  mysql:
    extends:
      file: ../common.yml
      service: mysql

  broker-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: broker-dev
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - ${SOURCE_PATH}/broker-service:/code
    command: reflex -r "\.go$" -s -- sh -c "dlv debug . --output=/tmp/__broker_debug_bin --listen=0.0.0.0:9091 --accept-multiclient --continue --headless --allow-non-terminal-interactive"

volumes:
  mysql:
    name: mysql

