version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    healthcheck:
      test: mysqladmin ping -proot
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    name: mysql