FROM golang:1.20.3-bullseye as dev

WORKDIR /code

ARG USER_ID
ARG GROUP_ID

# Create the user
RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    groupadd --gid ${GROUP_ID} devs \
    && useradd --uid ${USER_ID} --gid ${GROUP_ID} -m dev \
    && apt-get update \
    && apt-get install -y sudo \
    && echo dev ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/dev \
    && chmod 0440 /etc/sudoers.d/dev \
    ;fi

USER dev

# Install dependencies needed for local development
RUN go install github.com/cespare/reflex@latest
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install golang.org/x/tools/gopls@latest
RUN go install github.com/ramya-rao-a/go-outline@latest
RUN curl -sSf https://atlasgo.sh | sh

RUN sudo apt-get update && sudo apt-get install -y supervisor