version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    healthcheck:
      test: mysqladmin ping -proot
      interval: 3s
      timeout: 2s
      retries: 2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - db

  migrate:
    image: arigaio/atlas:latest
    command: migrate apply --url mysql://root:root@mysql:3306/ --revisions-schema portfolio
    networks:
      - db
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./portfolio-context/migrations/:/migrations

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile.Dev
      target: dev
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    image: portfolio-dev
    depends_on:
      migrate:
        condition: service_completed_successfully
    expose:
      - "8080"
      - "8181"
    ports:
      - "8080:8080"
      - "8181:8181"
    volumes:
      - .:/code
      - /var/run/docker.sock:/var/run/docker.sock
    command: reflex -r "\.go$$" -s -- sh -c "dlv debug ./portfolio-context --listen=0.0.0.0:8181 --accept-multiclient --continue --headless --allow-non-terminal-interactive"
    networks:
      - db

networks:
  db:

volumes:
  mysql:
