version: "3.8"

services:
  dev-environment:
    build:
      context: .
      dockerfile: Dockerfile.Dev
      target: dev
      # If using linux, you should set these in a .env file inside this (.devcontainer) directory
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID:-0}
    image: stock-trader-dev-environment
    tty: true
    environment:
      - SOURCE_PATH=$PWD
    volumes:
      - ..:/stock-trader
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  dev:
    name: stock-trader-dev-environment_network
