version: "3.8"

services:
  mysql:
    extends:
      file: ../common.yml
      service: mysql


  migrate:
    image: arigaio/atlas:latest
    command: migrate apply --url mysql://root:root@mysql:3306/ --revisions-schema portfolio
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${SOURCE_PATH}/portfolio-service/migrations/:/migrations

  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: portfolio-dev
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ${SOURCE_PATH}/portfolio-service:/code
    command: reflex -r "\.go$" -s -- sh -c "dlv debug . --output=/tmp/__portfolio_debug_bin --listen=0.0.0.0:9090 --accept-multiclient --continue --headless --allow-non-terminal-interactive"

volumes:
  mysql:
    name: mysql
