version: "3.8"

services:
  mysql:
    image: mysql:8.0.32
    healthcheck:
      test: mysqladmin ping -proot
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - stock-trader
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql

  migrate:
    image: arigaio/atlas:latest
    command: migrate apply --url mysql://root:root@mysql:3306/ --revisions-schema portfolio
    networks: 
      - stock-trader
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${SOURCE_PATH}/portfolio-service/migrations/:/migrations

  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: portfolio-dev
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      MYSQL_HOST: mysql
    volumes:
      - ${SOURCE_PATH:-$PWD}/portfolio-service:/code
    networks: 
      - stock-trader
    command: reflex -r "\.go$" -s -- sh -c "dlv debug . --output=/tmp/__portfolio_debug_bin --listen=0.0.0.0:9090 --accept-multiclient --continue --headless --allow-non-terminal-interactive"

volumes:
  mysql:
    name: stock-trader_mysql
    
networks:
  stock-trader:
    name: stock-trader_network
